services:
  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SITE_NAME=NextGen Bank
      - SECRET_KEY=/run/secrets/secret_key
      - ADMIN_URL=/run/secrets/admin_url
      - EMAIL_PORT=1025
      - EMAIL_HOST=mailpit
      - DEFAULT_FROM_EMAIL=NextGen Bank <noreply@nextgenbank.com>
      - DOMAIN=localhost:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=banker
      - DB_USER=dbuser
      - DB_PASS=/run/secrets/db_password
      - LOCKOUT_DURATION=1
      - OTP_EXPIRATION=1
      - BANK_NAME=NextGen Bank
    depends_on:
      db:
        condition: service_healthy
        restart: true
    secrets:
      - secret_key
      - admin_url
      - db_password

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=banker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dbuser", "-d", "banker"]
      interval: 30s
      timeout: 10s
      retries: 5
    secrets:
      - db_password

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - banker_mailpit_db:/data
    environment:
      - MP_MAX_MESSAGE=5000
      - MP_DATA_FILE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1


secrets:
  secret_key:
    file: ./secrets/secret_key.txt
  admin_url:
    file: ./secrets/admin_url.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  postgres_data:
  banker_mailpit_db: