# Generated by Django 5.2.1 on 2025-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_options_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='failed_login_attemps',
            new_name='failed_login_attempts',
        ),
    ]
