# Generated by Django 5.2.1 on 2025-06-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_nextofkin_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emplyer_city',
            new_name='employer_city',
        ),
    ]
