# Generated by Django 5.2.1 on 2025-07-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_emplyer_city_profile_employer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_currency',
            field=models.CharField(blank=True, choices=[('us_dollar', 'US Dollar'), ('pound_sterling', 'Pound Sterling'), ('kenya_shilling', 'Kenya Shilling')], max_length=20, null=True, verbose_name='Account Currency'),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('savings', 'Savings')], max_length=20, null=True, verbose_name='Account Type'),
        ),
    ]
